# Generated by Django 4.2.8 on 2024-03-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم')),
                ('floor_number', models.PositiveIntegerField(verbose_name='تعداد طبقات')),
                ('unit', models.PositiveIntegerField(verbose_name='تعداد واحد')),
                ('created_time', models.DateTimeField(verbose_name='سال ساخت')),
                ('parking', models.BooleanField(default=True, verbose_name='پارکینگ')),
                ('patio', models.BooleanField(default=True, verbose_name='حیاط')),
                ('lobby', models.BooleanField(default=True, verbose_name='لابی')),
                ('automatic_door', models.BooleanField(default=True, verbose_name='درب ریموت دار')),
                ('emergency_system', models.BooleanField(default=True, verbose_name='سیستم برق اظطراری')),
                ('Fire_alarm_system', models.BooleanField(default=True, verbose_name='سیستم اعلام حریق')),
                ('Powerhouse', models.BooleanField(default=True, verbose_name='موتورخانه')),
                ('cooler', models.BooleanField(default=True, verbose_name='کولر')),
                ('fire_capsules', models.BooleanField(default=True, verbose_name='کپسول آتش نشانی')),
                ('lighting_detail', models.TextField(verbose_name='سیستم روشنایی')),
                ('trashcans', models.PositiveIntegerField(verbose_name='سطل زباله')),
                ('Wastewater', models.BooleanField(default=True, verbose_name='فاضلاب')),
                ('elevator', models.BooleanField(default=True, verbose_name='آسانسور')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'موتورخانه'), (2, 'آسانسور'), (3, 'کولر')], verbose_name='نوع سرویس')),
                ('service_time', models.DateTimeField(verbose_name='زمان سرویس')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='building', to='app.building', verbose_name='ساختمان')),
            ],
        ),
    ]
